### ISSUE TITLE
MultiGPU Tensorflow

### ISSUE THREAD

**Issue by saonim** [aymericdamien/TensorFlow-Examples#16]
Hi,

When I run your [code](https://github.com/aymericdamien/TensorFlow-Examples/blob/master/examples/4%20-%20Multi%20GPU/multigpu_basics.py), instead of going to two GPUs, it takes over all that are available ( I have more than 2). How can I specify if I want to grab just two (say 4 and 5)?

**Comment by aymericdamien** [comment]
By default, Tensorflow will use all available GPUs, so to use some specific gpu, you have to use "CUDA_VISIBLE_DEVICES" flag, and specify all device ids that you want to use. For example:  CUDA_VISIBLE_DEVICES=0,1

**Comment by saonim** [comment]
Thanks for your response. With multi-GPU setting, it allocates on all available (or if specified, those) devices (GPU Memory usage is high on Nvidia-smi), but does not do computations (no memory utilization from Nvidia-smi while the program is running) on none except one. Any suggestion to make it truly parallel?

**Comment by aymericdamien** [comment]
Yes, because you have to allocate yourself operations to specific gpu, Tensorflow can't do it automatically.
```
with tf.device('/gpu:0'):
   ...
with tf.device('/gpu:1'):
   ...
```

But in order to efficiently use multiple GPU to train neural networks, you have to coordinate training. I suggest you check the official tutorial, they update parameters synchronously after each GPU finished to process a batch of data.
https://www.tensorflow.org/versions/r0.7/tutorials/deep_cnn/index.html#training-a-model-using-multiple-gpu-cards

![image](https://cloud.githubusercontent.com/assets/10386605/13098032/6f3861d8-d561-11e5-93b3-a2dd6910080c.png)
